Company.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Company.BLL.Interfaces;
using Company.BLL.Repositories;
using Company.DAL.Models;
using Company.PL.Helpers;
using Company.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Reflection.Metadata;
using System.Threading.Tasks;

namespace Company.PL.Controllers
{
	[Authorize]

	public class EmployeeController : Controller
    { 
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;

      

        public EmployeeController(IUnitOfWork unitOfWork, IMapper mapper) // ask clr to create object from Employee repository
        {
       
            this.unitOfWork = unitOfWork;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index(string SearchValue)
        {
            IEnumerable<Employee> employees;
            if (string.IsNullOrEmpty(SearchValue))
                employees =await unitOfWork.EmployeeRepository.GetAll();
            else
                employees = unitOfWork.EmployeeRepository.GetEmployeesByName(SearchValue);

            // var employees = EmployeeRepository.GetAll();

            var MappedEmp = mapper.Map<IEnumerable<Employee>,IEnumerable<EmployeeViewModel>>(employees);


            return View(MappedEmp);
        }

        public IActionResult Create()
        {
           // ViewBag.Departments = DepartmentRepository.GetAll();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel EmployeeVM)
        {
            if (ModelState.IsValid) // serverv side validation 
            {   // maping || manual mapping
                //Employee mappEmployee = new Employee()
                //{ 
                // Name = EmployeeVM.Name,
                // Age = EmployeeVM.Age,
                // Salary = EmployeeVM.Salary,    
                // Email = EmployeeVM.Email,
                // PhoneNumber = EmployeeVM.PhoneNumber,
                // Address = EmployeeVM.Address,
                // IsActive = EmployeeVM.IsActive,
                // HireDate = EmployeeVM.HireDate,
                // DepartmentId = EmployeeVM.DepartmentId,
                //};

                // auto mapper
                var MappedEmp = mapper.Map<EmployeeViewModel, Employee>(EmployeeVM);
                MappedEmp.ImageName = DocumentSettings.UploadImage(EmployeeVM.Image,"Images");
                await unitOfWork.EmployeeRepository.Add(MappedEmp);
                int Result =await unitOfWork.Complete(); 
                if (Result > 0)
                {
                    TempData["Message"] = "Employee Is Created!";
                }
                //3. temp data => dictionary object 
                // transfer data from action to action 
              
                return RedirectToAction(nameof(Index));
            }
            return View(EmployeeVM);
        }

        // new details ((((((((( Employee ? employee ? ))))))))) 
        public async Task<IActionResult> Details(int? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var employee =await unitOfWork.EmployeeRepository.Get(id.Value);

            if (employee is null)
                return NotFound();
            var MappedEmp = mapper.Map<Employee, EmployeeViewModel>(employee);

            return View(ViewName, MappedEmp);
        }
        [HttpGet]
        // new details
        public async Task<IActionResult> Edit(int? id)
        {
            return await Details(id, "Edit");
            //if (id is null)
            //    return BadRequest();
            //var Employee = EmployeeRepository.Get(id.Value);

            //if (Employee is null)
            //    return NotFound();

            //return View(Employee);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit([FromRoute] int id, EmployeeViewModel EmployeeVM)
        {
            if (id != EmployeeVM.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var MappedEmp = mapper.Map<EmployeeViewModel, Employee>(EmployeeVM);

                    unitOfWork.EmployeeRepository.Update(MappedEmp);
                  await  unitOfWork.Complete();
                    return RedirectToAction(nameof(Index));
                }

                catch (Exception ex)
                {
                    //1. log execption
                    //2. friendly message
                    ModelState.AddModelError(string.Empty, ex.Message);

                }
            }
            return View(EmployeeVM);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] int id, EmployeeViewModel EmployeeVM)
        {
            if (id != EmployeeVM.Id)
                return BadRequest();
            try
            {
                var MappedEmp = mapper.Map<EmployeeViewModel, Employee>(EmployeeVM);

                unitOfWork.EmployeeRepository.Delete(MappedEmp);
               await unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return View(EmployeeVM);
            }

        }
    }
}

Company.PL/Controllers/RoleController.cs
using AutoMapper;
using Company.BLL.Repositories;
using Company.DAL.Models;
using Company.PL.Helpers;
using Company.PL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Company.PL.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly IMapper mapper;

        public RoleController(RoleManager<IdentityRole> roleManager, IMapper mapper)
        {
            this.roleManager = roleManager;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                var roles = await roleManager.Roles.Select(R => new RoleViewModel()
                {
                    Id = R.Id,
                    RoleName = R.Name,

                }).ToListAsync();
                return View(roles);
            }
            else
            {
                var role = await roleManager.FindByNameAsync(name);
                var MappedRole = new RoleViewModel()
                {
                    Id = role.Id,
                    RoleName = role.Name,

                };
                return View(new List<RoleViewModel>() { MappedRole });
            }

        }

        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel RoleVm)
        {
            if (ModelState.IsValid) // serverv side validation 
            {

                // auto mapper
                var MappedRole = mapper.Map<RoleViewModel, IdentityRole>(RoleVm);
                await roleManager.CreateAsync(MappedRole);

                return RedirectToAction(nameof(Index));
            }
            return View(RoleVm);
        }

        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var role = await roleManager.FindByIdAsync(id);

            if (role is null)
                return NotFound();
            var MappedRole = mapper.Map<IdentityRole, RoleViewModel>(role);

            return View(ViewName, MappedRole);
        }

        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit([FromRoute] string id, RoleViewModel RoleVM)
        {
            if (id != RoleVM.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    //var User = mapper.Map<UserViewModel, ApplicationUser>(UserVM);
                    var role = await roleManager.FindByIdAsync(id);
                    role.Name = RoleVM.RoleName;


                    //user.Email = UserVM.Email;
                    //user.SecurityStamp = Guid.NewGuid().ToString();

                    await roleManager.UpdateAsync(role);
                    return RedirectToAction(nameof(Index));
                }

                catch (Exception ex)
                {
                    //1. log execption
                    //2. friendly message
                    ModelState.AddModelError(string.Empty, ex.Message);

                }
            }
            return View(RoleVM);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, RoleViewModel RoleVM)
        {
            if (id != RoleVM.Id)
                return BadRequest();
            try
            {
                var role = await roleManager.FindByIdAsync(id);
                await roleManager.DeleteAsync(role);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return View(RoleVM);
            }


        }
    }
}

Company.PL/Controllers/UserController.cs
using AutoMapper;
using Company.BLL.Interfaces;
using Company.BLL.Repositories;
using Company.DAL.Models;
using Company.PL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Company.PL.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly IMapper mapper;

        public UserController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IMapper mapper)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index(string email)
        {
            if (string.IsNullOrEmpty(email))
            {
                var users = await userManager.Users.Select(U => new UserViewModel()
                {
                    Id = U.Id,
                    FName = U.FName,
                    LName = U.LName,
                    Email = U.Email,
                    PhoneNumber = U.PhoneNumber,
                    Roles = userManager.GetRolesAsync(U).Result
                }).ToListAsync();
                return View(users);
            }
            else
            {
                var user = await userManager.FindByEmailAsync(email);
                var MappedUser = new UserViewModel()
                {
                    Id = user.Id,
                    FName = user.FName,
                    LName = user.LName,
                    Email = user.Email,
                    PhoneNumber = user.PhoneNumber,
                    Roles = userManager.GetRolesAsync(user).Result

                };
                return View(new List<UserViewModel>() { MappedUser });
            }

        }

        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var user = await userManager.FindByIdAsync(id);

            if (user is null)
                return NotFound();
            var MappedUser = mapper.Map<ApplicationUser, UserViewModel>(user);

            return View(ViewName, MappedUser);
        }

        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");

        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit([FromRoute] string id, UserViewModel UserVM)
        {
            if (id != UserVM.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    //var User = mapper.Map<UserViewModel, ApplicationUser>(UserVM);
                    var user = await userManager.FindByIdAsync(id);
                    user.FName = UserVM.FName;
                    user.LName = UserVM.LName;
                    user.PhoneNumber = UserVM.PhoneNumber;

                    //user.Email = UserVM.Email;
                    //user.SecurityStamp = Guid.NewGuid().ToString();

                    await userManager.UpdateAsync(user);
                    return RedirectToAction(nameof(Index));
                }

                catch (Exception ex)
                {
                    //1. log execption
                    //2. friendly message
                    ModelState.AddModelError(string.Empty, ex.Message);

                }
            }
            return View(UserVM);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, UserViewModel UserVM)
        {
            if (id != UserVM.Id)
                return BadRequest();
            try
            {
                var user = await userManager.FindByIdAsync(id);
                await userManager.DeleteAsync(user);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return View(UserVM);
            }
        }
    }
}

Company.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
    <link href="~/css/_authstyle.css" rel="stylesheet" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative @ViewData["Title"] Form</h1>
		@RenderBody();
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	@await RenderSectionAsync("ValidationScriptSection",required:false)
</body>
</html>

Company.PL/Views/Shared/_ButtonsPartialView.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model string
<td>
    <a asp-action="Details" class="btn btn-warning" asp-route-id="@Model">
        <i class="fas fa-eye"></i>Details
    </a>
</td>
<td>
    <a asp-action="Edit" class="btn btn-success" asp-route-id="@Model">
        <i class="fas fa-pencil"></i>Edit
    </a>
</td>
<td>
    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model">
        <i class="fas fa-trash"></i> Delete
    </a>
</td>

Company.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Company.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>

                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Company.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScriptSection",required:false)
</body>
</html>